### ISSUE TITLE
建议设置一下并发连接数

### ISSUE THREAD

**Issue by lupus721** [TideSec/FuzzScanner#2]
最好限制一下masscan的并发数，昨天开扫，带宽100m，连接数直接把交换机堵死了

**Comment by TideSec** [comment]
这个可以自己加个参数~我会在后期版本中加入这个~~谢谢

**Comment by TideSec** [comment]
我设置了一个scan_thread = 3000，可以自己根据自己情况修改下~不过我的扫描没有使用masscan，masscan准确度偏低，所以我用的socket探测端口开放~扫描的线程就是scan_thread的设置值~

**Comment by lupus721** [comment]
ok,3q
