### ISSUE TITLE
kali安装后不能启动nmap

### ISSUE THREAD

**Issue by BrathonBai** [TideSec/FuzzScanner#7]
报错信息：
root@kali:~/FuzzScanner# sudo python FuzzScanner.py 
Traceback (most recent call last):
  File "FuzzScanner.py", line 11, in <module>
    import urllib,nmap
ImportError: No module named nmap

**Comment by TideSec** [comment]
这个是需要安装nmap库，执行pip install nmap即可。

**Comment by flyballon** [comment]
> 
> 
> 这个是需要安装nmap库，执行pip install nmap即可。

安装后还是不行，还是提示这个错误，啥情况
